version: '3'
networks:
  app-network:
    driver: bridge

services:
  filmoteka:
    build:
      context: ./..
      dockerfile: filmoteka.dockerfile
    restart: always
    ports:
      - "8080:80"
    environment:
        DSN: "host=postgres port=5432 user=postgres password=postgres dbname=filmoteka sslmode=disable"
    deploy:
      mode: replicated
      replicas: 1
    networks:
      - app-network


  postgres:
    image: postgres:14.0
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: filmoteka
    volumes:
      - ./dbdata/postgres:/var/lib/postgresql/data/
    deploy:
      mode: replicated
      replicas: 1
    networks:
      - app-network